### ISSUE TITLE
Singelton error

### ISSUE THREAD

**Issue by codecat15** [hardipgajera/HackerNews#12]
I see that you are trying to use parameter-based dependency here, but really the news store is a singleton class and can be used directly in the view model without passing it from the view

That's the merit and de-merit of a singleton to be honest, if you search google you will learn that the ease of use of a singleton pattern has made it famous among developer but it really has become an anti-pattern which senior devs and architects would always advice to avoid

https://github.com/hardipgajera/HackerNews/blob/052a2c10531e39970427725e06a132830aab37a3/HackerNews/ViewModal/HomeViewModal.swift#L25

**Comment by hardipgajera** [comment]
Fixed this. but one question this is not look like hidden dependency ?
why it's not good idea if we pass it in constructer ?
