### ISSUE TITLE
Any reason for specifically using dispatch background?

### ISSUE THREAD

**Issue by codecat15** [hardipgajera/HackerNews#13]
https://github.com/hardipgajera/HackerNews/blob/052a2c10531e39970427725e06a132830aab37a3/HackerNews/ViewModal/HomeViewModal.swift#L54

**Comment by hardipgajera** [comment]
It is going to call an API so i think it would be better if this work happens in background.

**Comment by hardipgajera** [comment]
that time i don't know it;s always going in background for URLSession
