### ISSUE TITLE
Too many lines

### ISSUE THREAD

**Issue by codecat15** [hardipgajera/HackerNews#2]
I am sure this function does what it does but the code is not readable and it's doing too many things maybe you want to create few more abstraction layer to be clear on what this function is actually doing

https://github.com/hardipgajera/HackerNews/blob/2aeaa65f8ad2b974eb5b030dde13b5de43a300b2/HackerNews/ViewModal/HomeViewModal.swift#L41

**Comment by hardipgajera** [comment]
i don't know about URLSession is in background bydefault. so i dispatch every API call on background
