### ISSUE TITLE
Singleton

### ISSUE THREAD

**Issue by codecat15** [hardipgajera/HackerNews#5]
I am assuming you are using this as a resource abstraction like how I show in my videos, but it's a singleton and is going to live in the memory even after the view is deallocated which is not a good approach, just drop the private init and you should be good no need for a singleton class here.

This is not the right place coz, once your view is out of the memory you want all the objects to be deinitalized and not to be in the memory even after the view is dead.

I have made a couple of videos on how singleton are abused by developers, best if you watch my core data videos over there you will know how creative developers use singleton as a ManyTon object and justify their crime of abusing a wonderful pattern.

https://github.com/hardipgajera/HackerNews/blob/052a2c10531e39970427725e06a132830aab37a3/HackerNews/Stores/NewsStore.swift#L18

**Comment by hardipgajera** [comment]
Ok i will consider this.
