### ISSUE TITLE
fatalError are a big NO

### ISSUE THREAD

**Issue by codecat15** [hardipgajera/HackerNews#7]
What if an error happens? with a fatalError message you are causing the app to crash, we don't want the app to crash if an error occurs we want to gracefully handle it so that the user does not have any bad experience in the app

https://github.com/hardipgajera/HackerNews/blob/052a2c10531e39970427725e06a132830aab37a3/HackerNews/Stores/NewsStore.swift#L29

**Comment by hardipgajera** [comment]
Ya sure..

**Comment by hardipgajera** [comment]
remove fatalerror. Not doing alert stuff. but now more less chance to crash an application
