### ISSUE TITLE
Function name

### ISSUE THREAD

**Issue by codecat15** [hardipgajera/HackerNews#9]
The function name is getStoreiesFromID but the escaping closure returns one Model so it's singular and not plural, unless you are returning something like Array<NewsModel> so rename the function to "getNewsStoryFromId" always use camel case

https://github.com/hardipgajera/HackerNews/blob/052a2c10531e39970427725e06a132830aab37a3/HackerNews/Stores/NewsStore.swift#L34

**Comment by hardipgajera** [comment]
Yaa. this is wrong thank to suggest me.
